name: Sync Images

on:
  push:
    paths:
      - 'images/**'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Process Images
        run: |
          cd images

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add images/
          git commit -m "Sync images" || echo "No changes to commit"
          git push
